### ISSUE TITLE
Bounding box realignment for face_id 3 placed incorrectly

### ISSUE THREAD

**Issue by ktlhtn** [keevin60907/mp-YOLO#2]
When realigning the bounding box coordinates from the faces (subimages) back to the equirectangular video frame, the detections / bounding boxes for face_id == 3 are calculated incorrectly. Apparently the realign_bbox function calculates face_id 3 bounding boxes over the right edge of the equirectangular frame, when they should be calculated to the leftmost  side. 

For clarification: the realign_bbox function logic assumes that the faces on the equirectangular frame are in this order (from left to right within the frame): 0, 1, 2, 3 when they actually are in this order: 3,0,1,2. I fixed the issue in my use by adding the following lines to the beginning realign_bbox function:

    if face == 3:
    	face = -1

It's not the most sophisticated fix, but it did the trick. 

This bug can be reproduced by processing equirectangular frames with objects to detect on all faces. The end result of the processing is that bounding boxes for the detections on the leftmost sector on the frames are not visible.

**Comment by keevin60907** [comment]
I fixed the bug with the trick you mentioned, thanks!
